### ISSUE TITLE
Menu not finding USB drive

### ISSUE THREAD

**Issue by iglesiasmarianod** [Openvario/meta-openvario#12]
Hi guys, I've fixed a misnomer in the Menu scripts to allow file download from OV to USB and added an option to delete all igc stored files.
Also added a Spanish language option to the menu.
Works OK with previous OV buildsystem, now it seems it does not mount USB drives.
If you'd like to have a look to the scripts please, I issued a pull request from my branch.
Let me see if I can figure out why USB seems not to mount.

Regards.

**Comment by linuxianer99** [comment]
The reason for the missing USB drive is a missing auto-mounter in the image. It was not ported up to now to the warrior based image.
We can do this in the future, but i suggest, we will release an preview image now.

In the next release, we can fix the missing things discovered during tests with the image ...

**Comment by iglesiasmarianod** [comment]
Hi Timo! It's OK for me.
I agree these mods can be included in the future.
