### ISSUE TITLE
Release new official image

### ISSUE THREAD

**Issue by kedder** [Openvario/meta-openvario#130]
It's been a while since we released the official image. I suggest cutting a new release, after new XCSoar 7 was released.

**Comment by linuxianer99** [comment]
@kedder : Will try to manage this in the next few days ...

**Comment by hpmax** [comment]
How is this coming?  Is a CH070 image available yet?

**Comment by linuxianer99** [comment]
Created some scripts for automation the last few days ...
Hopefully tomorrow i can start the build ...

**Comment by linuxianer99** [comment]
Builds are running ...
Think we don't need -DS2 images at the moment ?? It will double the build time for release ...

**Comment by Developer66** [comment]
Is there any fix for issue  #97 in the new version? 

We have two Stelfy with 201903 in different planes with the same vario behaviour. Several Variopeeks with +-5m/s while flying.

**Comment by linuxianer99** [comment]
@kedder : variod and sensord have no new release right now. 
So the stable image will have the already released versions, but the testing image has the bleeding edge version.

Think this is intentional, right ??

**Comment by kedder** [comment]
well, yes, I think those bleeding edge versions were never actually tested, so I'd expect them in the testing version. Hopefully more people will try them out.

**Comment by hpmax** [comment]
@Developer66 I honestly don't remember exactly what was going on with that, I know that running Version 6.x of xcsoar had issues.  I believe the latest versions of variod and sensord are working as well as they are going to before the new hardware is introduced.

**Comment by Developer66** [comment]
@hpmax I also dont know whats going on/wrong. We had these Vario Peeks while flying straight or in thermal. The Vario jumps to +-5m/s and goes back to a normal value. Tested on two Stefly on differnt planes with same software.
So there must be some Software issue with that. ;(

**Comment by hpmax** [comment]
@Developer66 Honestly, I've lost interest in the old hardware.  I'm just starting development of software for the new software.  Let's try out the new release and if it's working call it a day, otherwise I'll try to hack together a fix.

@linuxianer99 it looks like the new release is out, but no images... will they be coming shortly?

**Comment by linuxianer99** [comment]
@hpmax : Please be patient ... Yesterday, kernel.org download have been failed ... Server not reachable ..

**Comment by linuxianer99** [comment]
@kedder : Built the openvario-7-PQ070 machine an hour ago. Both images have only 7,5MB ... openvario-7-CH070 has about 80MB. Content seems to be 1,2GB in both cases .... 
But looks strange to me ... any idea ??

**Comment by hpmax** [comment]
BTW, is there any reason why the file space is so small?  SD cards are pretty cheap these days.  In fact, I don't think cards are typically less than 16GB.  Doesn't seem like an unreasonable requirement to put on it.

**Comment by kedder** [comment]
@linuxianer99 hm, I'm not sure, but I noticed that when I build an image without any changes on the same day, I have this almost empty image. Not sure if that's the case here too, but you can try rebuilding `openvario-7-CH070`. If you get the 7.5MB image, then you're hitting the same thing.

@hpmax there is no requirement, there's just nothing to put on the image. The normal image size should be around 80MB.

**Comment by linuxianer99** [comment]
@kedder : I build all machines in seperate build folders. Just to avoid such problems ... Hmmm ....
Will delete the folder and try again ...

**Comment by hpmax** [comment]
Not to obnoxious or pushy, but has there been any progress?

**Comment by linuxianer99** [comment]
Still have the problem with the small image file size...
Tried a lot of things now ...

Nevertheless, is published the release and added the artifacts, which are looking good ... Rest will follow ..

**Comment by Developer66** [comment]
Anything new about the openvario-57-lvds release?
Thanks

**Comment by linuxianer99** [comment]
@Developer66 : I tried again ... But the image is still only 6MB of size.
Nevertheless, can you please try flashing it ?? But be prepared to remove the SDCard ;-)

Thanks,
Timo
[OpenVario-linux-openvario-image-glibc-ipk-21118-openvario-57-lvds.rootfs.img.gz](https://github.com/Openvario/meta-openvario/files/6566552/OpenVario-linux-openvario-image-glibc-ipk-21118-openvario-57-lvds.rootfs.img.gz)

**Comment by Developer66** [comment]
Unfortunately the file did not work :(
@linuxianer99

**Comment by saxthi** [comment]
Anything new about the openvario-57-lvds release?
Thanks

**Comment by linuxianer99** [comment]
Hey All!
I talked to a friend of mine, who is expert in Openembedded and bitbake. He gave me some tipps for this issue. I will try to check these in the next few days ... Hopefully this solves the issue ...

**Comment by linuxianer99** [comment]
ok! So the openvario-image is uploaded for all platforms.
Testing relase is not building because of XCSoar. i will have a look on this.
@Developer66, @saxthi : Can you please test the release ??

**Comment by saxthi** [comment]
Hi all, I just loaded it without any problems. I also loaded the right map but did not do any further checking…

Thanks!!

**Comment by linuxianer99** [comment]
Great to hear !!
So how should we proceed with the testing version ?
Purpose was to have the latest XCSoar there ...

Maybe we can do a release with the latest buildable XCSoar within this base version of Openembedded ??
@kedder , @Developer66 : Do you know, what was the last version building with the used compiler ?

**Comment by linuxianer99** [comment]
ok!
so i compiled XCSoar 7.15 for the testing release.
Feel free to check :-)

Think i close this ticket ;-)

**Comment by Developer66** [comment]
Thank for your work!

I will give this a try in the next weeks.
