### ISSUE TITLE
Undocumented Keyboard Shortcuts

### ISSUE THREAD

**Issue by h4ckerle** [Openvario/meta-openvario#131]
Whilst trying to build a [Dual Rotary Encoder with Pushbuttons](https://www.openvario.org/doku.php?id=projects:series_00:electrical_tests:dual_rotary_encoder) i came across some undocumented Keyboard Shortcuts which are seemingly not doing anything. In the Script i downloaded there are Shortcuts for things like _t_, _z_, _x_, _p_, _o_, _i_, _q_. Is there a list of all available Keyboard Shortcuts? Or can somebody at least tell me what these are used for?
TiA

**Comment by kedder** [comment]
Are you talking about shortcuts of XCoar? Where have you found them?

**Comment by h4ckerle** [comment]
Thanks, ill have a look there.
