### ISSUE TITLE
update environment

### ISSUE THREAD

**Issue by Scumi** [Openvario/meta-openvario#138]
XCSoar has gotten some updates in the last few days, now requiring GCC >10.0 and lua5.4 (potentially others as well). The openvario build environment currently fails to build XCSoar unless those dependencies are updated.

**Comment by kedder** [comment]
I'm trying to upgrade the build environment to yocto "hardknott" release (latest one) to see what happens.

**Comment by linuxianer99** [comment]
@kedder :
Good thing!! Maybe that solves also the build issue with the failing images ....

**Comment by kedder** [comment]
Some status update on this effort: I'm at the stage where everything compiles, but the image does not boot. The old u-boot does not compile under new environment and newer u-boot needs to be reconfigured.  This is what I'm working on.

**Comment by hor63** [comment]
@kedder I had the same problem with my Ubuntu based BSP here. I just created a new config from the cubieboard 2 defconfig, and it worked OOTB.
Or take it [from my BSP here](https://github.com/hor63/horOpenVario/tree/mainline-debootstrap/build/u-boot).

**Comment by kedder** [comment]
I've got the system booting, xcsoar seems to be working. The main problem left is that the boot process is not pretty: u-boot outputs a lot of logs. I want to make it prettier by hiding it behind the splash screen, but couple of different things I tried didn't work.

That said, interesting project you've got there!

**Comment by Blaubart** [comment]
Any news about compiling XCSoar?

**Comment by lordfolken** [comment]
Yes i'd also be interested.  I would love to integrate the openvario build in the regular build chains we use for debugging etc. I can provide knowledge in github actions, containers and even build infrastructure. 

The container build is already a good start. But we need a new compiler. There also have been some dependenciy changes in xcsoar, have a look at: 
https://github.com/XCSoar/XCSoar/blob/master/ide/provisioning/install-debian-packages.sh

Mostly up2date build instructions are here: 
https://github.com/XCSoar/XCSoar/blob/master/doc/build.rst

**Comment by lordfolken** [comment]
Also adding kedders openvario menu / compman would be excellent.

**Comment by lordfolken** [comment]
Maybe taking the ubuntu ( i would prefeer debian) approach like @hor63 did would ease the maintenance of the os.

**Comment by Blaubart** [comment]
If I understand correctly XCSoar 7.15 can be compiled. How can I adjust to compile XCSoar 7.15?

**Comment by lordfolken** [comment]
I suggest we update the yocto layer to hardknott, i'm currently running tests to that. (hardknott is the latest supported by sunxi)
is pulseaudio still needed? It seems to be now part of poky/hardknott/recipes-multimedia
What is missing still is autofs. 
And we have to see what patches are still needed for the kernel

**Comment by kedder** [comment]
@lordfolken I did an upgrade to hardknott in my fork at https://github.com/kedder/meta-openvario/tree/hardknott. Everything is more or less working there except the bootloader initializing in not very pretty way. I'm having trouble finding time to debug it.

pulseaudio is needed to support vario sounds as well as to mix with xcsoar internal sounds (It doesn't mean we can't use one that comes with OE.

**Comment by lordfolken** [comment]
ok i'm compiling your layer now. Maybe make a pr here and mark it as draft? 
then we could rebase.

**Comment by lordfolken** [comment]
https://github.com/linux-sunxi/meta-sunxi/issues/332 This would enable us to go to horister yocto environment.

**Comment by August2111** [comment]
I see a lot of efforts in several directions to bring the openvario to fly with the next yocto version (hardknott or honister). Some days ago I start with a lot of investigations to understand the yocto setup :)
The single package with XCSoar 7.20 I created 3-4 weeks ago for all the machines, but because I don't have a testing machine on my working place I couldn't test it ;-( 
But end of the day we need a complete image for all the machines - and as kedder said, there are some problems with the u-boot. Now it seems to be solved  :), but unfortunately I need some days (around 1 or 2 weeks) to bring all my staff together for a new PR.
Maybe an other guy is faster then me - very nice: I learned really a lot about the setup of the whole packages - and we don't will having such a long gap in our development...

Hopefully next week I will present this new openvario image!

**Comment by lordfolken** [comment]
Just so you know: an image isn't that valuable. We need the process that builds it.

**Comment by August2111** [comment]
Of course, you are completely right :)
Exactly this makes some more time - and this is the reason too, that I havn't published the XCSoar 7.20 IPK package. At the end of the story you will get the complete flow of this, with 'repo'  staff, Dockerfile, U-Boot changes (unfortunately there is something changed...) and so on.
I had started with hardknott too - like kedder, and this is enough for the next generation...
But later I will change to Honister, this is for us a small step

**Comment by August2111** [comment]
Now I have compiled and 'imaged' the  complete OpenVario package with Hardknott, this I have published at https://github.com/August2111/OpenVario/releases only as a draft - maybe you can try it (unfortunately I don't have any hardware here yet and have to organize a testing setup in the next days ;-( 
The next step is to make the commit order more readable and in easier to understand ..

**Comment by August2111** [comment]
I am very happy to announce. that the new Image 21336 starts and runs on my real OpenVario (in my case AM070-DS2) with XCSoar 7.20! This also seems to solve the U-Boot problem ... 
The yocto version is 3.3 (Hardknott) - among other things, the LUA update to 5.3.6 took place, but Honister does not have a newer version either ;-(
 For test purposes I have already tried the newest LUA 5.4.3, but that is still pretty preliminary - and not yet in the published version 21336!

**Comment by August2111** [comment]
Unfortunately i named the release tag like the planned branch - so I renamed the release tag to v21336 - so you can find the images and packages from yesterday at the new url https://github.com/August2111/OpenVario/releases/tag/v21336

On repository https://github.com/August2111/OpenVario you can find all my scripting staff to build this image: f.e. run-docker.py I use to get all the needed layer branches from yocto, openembedded, sunxi and openvario - like repo is doing, but with lokal setting possibility - and build-image.py is a python script to start the building of the image ( here you have to set the MACHINE inside the script...) Maybe you can play with this scripts a little bit, the benefit is here: You don't need to wait of changes in the GitHub repositories!

But at end of the day all this things should be back in the GitHub action like Timo is doing - with the best case, that you need only one command to build the images on your local system

**Comment by linuxianer99** [comment]
So @August2111 has finished porting the meta-openvario to hardknott #143 .
Also a new build container is available since a few days.

If all test builds are working well, i think we can close this issue ??!!

@kedder @August2111 : Your opinion ?

**Comment by August2111** [comment]
The building environment  is on the track yet  :)
At further problems we should create a new issue - from my point of view this can be closed!

If you have a really running system I want to give a short statement in the forum too...

**Comment by kedder** [comment]
@linuxianer99 totally agree!
