### ISSUE TITLE
Maps Checksums invalid during build

### ISSUE THREAD

**Issue by lordfolken** [Openvario/meta-openvario#139]
https://github.com/Openvario/meta-openvario/blob/57ccb1bf533e275be7cd561254633a93316639c4/recipes-apps/xcsoar/xcsoar-maps-alps_0.1.bb#L20
The maps get now updated regularly. So hardcoding the checksums here will fail. Can you source a checksum's file ? I could create one.

**Comment by linuxianer99** [comment]
Hey. Yes, it should be possible to specify a checksum URI [link](http://www.burtonini.com/blog/2017/06/13/dynamic-source-checksums/)

Would be great, if you generate these files for us !!

**Comment by linuxianer99** [comment]
@lordfolken : Any progress on this ??
Would be a good chance to have this in the new hardknott layer ;-)

**Comment by lordfolken** [comment]
Waiting for https://github.com/XCSoar/xcsoar-data-maps/commit/da2344b46fe005a04867dcca77a96314860c43f3
to complete. Then we will have .sha256 files in http://download.xcsoar.org/maps/

**Comment by lordfolken** [comment]
@linuxianer99 ok the checksums are now online in http://download.xcsoar.org/maps/ for example:
http://download.xcsoar.org/maps/ALPS_HighRes.xcm.sha256

There are some outdated airspace and flarmnet files. I'm not sure what to do about those, and i have no influence on them.

**Comment by August2111** [comment]
From my point of view we should remove all recipes `xcsoar/xcsoar-maps-*.bb`: As lordfolken mentioned there are some very old and outdated data in (f.e. in maps-alps the airspace file from Austria 2011!)
We should use only one `xcsoar-data.bb` recipe with all data files for a clean XCSoarData directory with the default map file, default profile and such data files... (f.e. lua examples!) I think the better solution is to make it easy to download this current files from internet...
If you are agree with this I will prepare a PR with my proposal...

Of course we can switch off the hashsum check (f.e. with BB_HASHBASE_WHITELIST...) or we make a lot of affort to synchronize the checksums - but all this staff is never needed I think!

**Comment by lordfolken** [comment]
I think its a good thing that there is a map in the image. I have a kind of a plan to do this for other XCSoar platforms as well. Would prevent the white screen currently greeting new users. So by all means keep a few maps in there. 

Airspace etc is all highly variable data. There it makes less sense to supply with the image. The question is: what is the process for the (offline) end user to get this data?

**Comment by August2111** [comment]
> I think its a good thing that there is a map in the image. I have a kind of a plan to do this for other XCSoar platforms as well. Would prevent the white screen currently greeting new users. So by all means keep a few maps in there.

I totally agree with you - and for this OpenVario have a `openvario_default.xcm` in the data path - and loaded with the profile :) This is showing on start at a really fresh image. Most of the guys know, where to get the correct map - either with a filled USB stick or with an internet connection (wired or wifi). And this default-map is a must for the delivery package! But I want to skip the affort for all other data files ...

In my club in the next yearI want to update all OV devices with an WLAN stick - and we have a functional WLAN on our whole airfield, so it is easy to download everything itself. Besides, one can upload IGC files and download task and all this things - this will be the future. 
So we don't need so much installation data, only some small ones, that everyone can easy see how it works!
For the offline guys the USB memory stick is still available and descript...

**Comment by linuxianer99** [comment]
The idea behind all this maps packages was a long time ago ....
We wanted to update the complete flight computer using a package based approach ... So also the maps ...
But i think this was not used often, so i agree to just deliver a base map with the image ...

On the other hand, we can use the github actions to automatically build the new maps as ipks. So installation via "standard" opkg and usb stick is possible for the "offline" flight computers ??

**Comment by August2111** [comment]
I don't know...
In the beginning of OpenVario this was a very good idea - but now? I prefere the handling of maps and other data inside the XCSoar software completely - not the indirection/detour with the OV menu...

**Comment by linuxianer99** [comment]
ok. Also fine for me :-)

Think also, we should think about the packet based update method ...  Maybe we do this just for selected packages like XCSoar, but not for the whole OS.
I will create a seperate ticket for this discussion ...

@August2111 @lordfolken : So we close this ticket and continue the update concept in #148
