### ISSUE TITLE
openvario bootup animation isn't rotated

### ISSUE THREAD

**Issue by lordfolken** [Openvario/meta-openvario#146]
The bootup animation isn't being rotated

* The first screen is displayed correctly "Openvario: Starting"
* Then the openvario bootup with progressbar is displayed for about 1 second.
* After this follows a 10s of complete darkness. 
* Thereafter the openvario menu is displayed all correctly rotated

[![Video Demonstration](https://img.youtube.com/vi/iQ03z0RqzaQ/hqdefault.jpg)](https://www.youtube.com/embed/iQ03z0RqzaQ)

Rotation: Portrait 90 Degree

```bash
Build Configuration:
BB_VERSION           = "1.50.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "arm-ovlinux-linux-gnueabi"
MACHINE              = "openvario-57-lvds"
DISTRO               = "ovlinux"
DISTRO_VERSION       = "21343"
TUNE_FEATURES        = "arm armv7ve vfp thumb neon callconvention-hard"
TARGET_FPU           = "hard"
meta                 
meta-poky            
meta-yocto-bsp       = "HEAD:7edd2be25fdf72187738fc551235df0f24e918bb"
meta-sunxi           = "HEAD:612de90a00fbd89762e3d85d85c6846fdc1f9ef6"
meta-openvario       = "HEAD:7c349522ada91ccae88766593fe3da4af2b22b3e"
meta-oe              
meta-python          
meta-networking      = "HEAD:f72a73b42fa740130b388ba8555cdbefdee8d37d"
```

**Comment by August2111** [comment]
I saw this 2nd part of boot 'bootup animation' the 1st time here, up to now I don't know, when this displaying starts: In the u-boot or in the startup of linux...
I will look inside too! Maybe we can the long black time shorten or - better - complete switch off ;-)

**Comment by lordfolken** [comment]
So with the recent builds, the "times of darkness" are reduced quite a bit.

For the splash screen rotation i have a solution in #201. 

Still the screen going dark after uboot, leaves a large uncanny valley. and its the first impression we give to the user.

**Comment by linuxianer99** [comment]
@lordfolken Should we make another ticket as enhancement:

Improve user experience during bootup sequence 

?

**Comment by lordfolken** [comment]
yes, i would agree also that this is belongs in a new ticket.
