### ISSUE TITLE
Texim 7" display doesn't work

### ISSUE THREAD

**Issue by kedder** [Openvario/meta-openvario#16]
Users are reporting that 7" Texim display doesn't work with the recent (20067) image.

>  Here's a video of non-working image: https://drive.google.com/open?id=1qQbzZW6G60sZAgtfYW7ZHiwC8yZA5LGY

Apparently 7" Texim has different resolution (800x480) than PixelQi one (1024x600). So devicetree files we provide are obviously wrong. U-boot configuration is also wrong. 

We need to pick the right timings from old fex file.

See `recipes-kernel/linux/linux-mainline/openvario-7-CH070.dts`, `recipes-bsp/u-boot/files/openvario-7-CH070/openvario_defconfig`.

**Comment by kedder** [comment]
Testing image to try for 7" Texim users is here: https://www.dropbox.com/s/ahj0s0oel3qqo0z/OpenVario-linux-openvario-image-glibc-ipk-20069-openvario-7-CH070.rootfs.img.gz?dl=0

Please try and report back!

Made from my fork at https://github.com/kedder/meta-openvario/tree/warrior-ch070.

**Comment by bomilkar** [comment]
Hi kedder, just tested your image OpenVario-linux-openvario-image-glibc-ipk-20069-openvario-7-CH070.rootfs.img.gz.
Scaling seems to be off, at least for me. See attached pictures.
I verified the H/W with an old image (a copy of SDcard from my glider). This works as expected.
![p0](https://user-images.githubusercontent.com/20871255/77222259-098dce00-6b52-11ea-9734-0aae93b0c7dd.jpg)
![p1](https://user-images.githubusercontent.com/20871255/77222263-0a266480-6b52-11ea-8917-a4f132a83e2b.jpg)
![p2](https://user-images.githubusercontent.com/20871255/77222264-0a266480-6b52-11ea-8d5c-cfc09b481316.jpg)
![p3](https://user-images.githubusercontent.com/20871255/77222266-0abefb00-6b52-11ea-980a-a011aa33b951.jpg)

**Comment by kedder** [comment]
@bomilkar can you double-check the image you have used? My image comes with xcsoar 7.0-preview12, not preview14 on your screenshots.

**Comment by bomilkar** [comment]
You are right. I must have screwed up writing the SDcard. The 2nd partition must have survived from a previous test. Your hint with "preview14" made me think ...
Now it works as expected. Thanks!
