### ISSUE TITLE
Enable touch screen calibration / rotation

### ISSUE THREAD

**Issue by kedder** [Openvario/meta-openvario#17]
According to @mihu-ov, touch screen calibration and rotation doesn't work in 20067.

> touch works, but calibration / rotation matrix not activated?

**Comment by kedder** [comment]
The `caltool` that is intended to calibrate touchscreen seems to be broken. It segfaults when started with any `-r` parameter (intended for rotation). 

It doesn't run on laptop either: requires root to run and completely hangs, doesn't react to Ctrl-C and requires laptop reboot.

Fixing this requires access to hardware (which I don't posses, unfortunately). @linuxianer99, can you look into this?

**Comment by linuxianer99** [comment]
@kedder : Yes, i can do so. But nit before the weekend ...

**Comment by SashLi** [comment]
Is there any new information to this issue ?

**Comment by linuxianer99** [comment]
@kedder : the caltool used before is very fragile.
Maybe we can use tslib https://github.com/libts/tslib/blob/master/README.md#setup-and-configure-tslib instead ?
There is a possibility to emulate a "calibrated touch" via uinput in linux kernel.
Do you know if it is possible to set the input device XCSoar is using ?

**Comment by kedder** [comment]
@linuxianer99, I've never dealt with touchscreens before, so it is hard to say.  I'm not even sure what mechanisms/apis are involved in reading the touchscreen input. I can see tslib is included in `meta-oe`, so it should be easy to build it. But again, since I don't have the touchscreen hardware, I can't test it.

**Comment by linuxianer99** [comment]
I compiled tslib yesterday evening.
Installation worked fine but i need uinput kernel module. So i have to compile a new kernel for testing.

The only thing is, don't know if i can tell XCSoar to use the /dev/uinput instead of /dev/input/eventx ... We will see ;-)

**Comment by marulidu** [comment]
Just completed installation of new touchscreen unit and come across this issue since screen is installed at portrait, 270 orientation. Cursor stays at upper edge despite of touch area. Extremely disappointing. Touch feature became totally useless. I could be more then happy to contribute to software testing.

**Comment by linuxianer99** [comment]
@kedder : Think i have a solution for the touch:

Using tslib with tslib_uinput:
tslib_uinput make a virtual event device with calibration and rotation information.

Things to do:
- disable real touch device for libinput using udev ENV.
`ACTION=="add|change", KERNEL=="event[0-9]*", ENV{ID_PATH_TAG}=="platform-1c25000_rtp", ENV{LIBINPUT_IGNORE_DEVICE}="1"`

- set Env variable `TSLIB_TSDEVICE=/dev/input/event5` to tell tslib which device to use.
- start tslib_uinput: This uses event5 and emulates event7 with all overlay features tslib can do (calibration, rotation, sensitivity, ...)

Do you think this is a useable approach ?

**Comment by kedder** [comment]
@linuxianer99, This won't require any change to XCSoar to support touch events via tslib, right? if it works, it looks great!

**Comment by linuxianer99** [comment]
@kedder : Yes, no changes to XCSoar.
Just udev things ... and a bit of configuration ...

**Comment by Blaubart** [comment]
I compiled the new image last night, but touch screen dosen't work. I can't calibrate touch screen. If I start the calibration tool I get the message touch screen is calibrated. If I start XCSoar I have no reaction about the touch screen.

**Comment by marulidu** [comment]
Same with mine. Actually touch moves cursor along upper edge only

**Comment by linuxianer99** [comment]
@Blaubart 
@marulidu 
Which type of image did you build ? openvario-testing ?
Which type of hardware do you have ?

**Comment by Blaubart** [comment]
I have a OV with Pixel Qi 7.0 and tried openvario-testing

**Comment by linuxianer99** [comment]
Can you please do the following:

- on the Openvario linux change to` /dev/input/by-path`
- Do a `ls -alh` and post this output here

**Comment by Blaubart** [comment]
![20-05-29 11-24-49 6505](https://user-images.githubusercontent.com/6558180/83251131-73a59d80-a1a9-11ea-96ba-021977e4a4dd.jpg)

**Comment by linuxianer99** [comment]
@Blaubart Do you have the possibility to change files config files in the linux system ?
Or do you need a full image for testing a fix ?

**Comment by Blaubart** [comment]
I can change files, no problem

**Comment by linuxianer99** [comment]
Try to change the following:

in `/home/root/.profile`
from
`export TSLIB_TSDEVICE=/dev/input/event5`
to
`export TSLIB_TSDEVICE=/dev/input/by-path/platform-1c25000.rtp-event`

and
in `/etc/ts.env`
from
`TSLIB_TSDEVICE=/dev/input/event5`
to
`TSLIB_TSDEVICE=/dev/input/by-path/platform-1c25000.rtp-event`

**Comment by Blaubart** [comment]
Now I can calibrate the touch screen, but it dosen't react to my finger when XCSoar is running

**Comment by linuxianer99** [comment]
Did you do a reboot after the calibration ?
The thing is that there is a systemd service (ts_uinput) which needs to be restarted to apply the calibration. So the easiest way is to reboot.

**Comment by Blaubart** [comment]
Yes I did.

I don't know why, but now the arrow moves with touch screen. But at X-axis arrow moves just half way. At Y-axis arrow reaches the end of display but my finger moves just have way.

**Comment by kedder** [comment]
Thanks to Stephan Langer, who generously donated me the hardware for development, I have a 7" device with the touchscreen (and sensors too) and can play with it now!

I've checked out the image with the tslib support and found couple of issues:

1. The touchscreen is not always registering as `/dev/input/event5` - the number actually depends on how many other input devices (keyboards, mice, etc) are connected. If it is not on `event5`, ts_uinput will not start at all (therefore tochschreen won't work). We can use `/dev/input/by-path/platform-1c25000.rtp-event` instead, as @linuxianer99 suggested.

2. The touchscreen appears to work only for the first time XCSoar is started - if you exit and start the XCSoar again, touchscreen doesn't work until you restart ts_uinput service. Also, when it works, it does in somewhat weird way - the touch screen appears to be always "pushed", I can draw red lines on XCSoar map, and it will not process the gesture even when I'm not touching the screen anymore. Taps (clicks) are not registered - I can't select anything or bring up menu - just draw with the red line.
The `ts_uinput`, if run with `-v` switch would log the pressed coordinate even when XCSoar would not react to touchscreen.

3. The `TSLIB_TSDEVICE` env variable doesn't seem to have any effect on XCSoar, so there's no point to put it to `.profile` (unless I'm missing something)

I'll play with it a little bit more, maybe I'll be able to come up with something working.

**Comment by kedder** [comment]
I think I made tslib work, including screen rotation, but it is a bit hacky  (using `LIBINPUT_CALIBRATION_MATRIX` to force the rotation), so I'm not too happy with it just yet.

Without ``LIBINPUT_CALIBRATION_MATRIX` hack I've observed the same behaviour on rotated screen as @Blaubart, and this seems like a bug (or just missing feature) in tslib version we use right now (1.16). It seems like [1.18](https://github.com/libts/tslib/releases/tag/1.18) has some better support for screen rotation and I'll try to upgrade and see if it improves things.

**Comment by kedder** [comment]
Ok, I think I figured it out. @Blaubart, can you try this new image: [20164-openvario-7-CH070](https://www.dropbox.com/s/yg24eis0imqsvdh/OpenVario-linux-openvario-image-testing-glibc-ipk-20164-openvario-7-CH070.rootfs.img.gz?dl=0)?

The touchscreen should work in all 4 directions after calibration. First, pick your screen orientation, then reboot, then calibrate the touch screen, then start xcsoar.

**Comment by Blaubart** [comment]
Thats sounds good!! Thanks! I use a Pixel Qi 7, so can you send me the image for this display, please?

**Comment by kedder** [comment]
@Blaubart here you go: [20165-openvario-7-PQ070](https://www.dropbox.com/s/qjn74cevxexmynf/OpenVario-linux-openvario-image-testing-glibc-ipk-20165-openvario-7-PQ070.rootfs.img.gz?dl=0).

**Comment by Blaubart** [comment]
Hi Kedder,

it almost works ;-)
Touchscreen works really good, but calibration is not saved. If I restart OpenVario I have to calibrate again because touchscreen dosen't respond to the my finger. After calibrate again touchscreen works until I powered off the device.

Regards and thanks a lot!
Blaubart

**Comment by kedder** [comment]
@Blaubart yeah, apparently I didn't test it well enough. Please try the new image: [20167-openvario-7-PQ070](https://www.dropbox.com/s/771vn48kmbc2hm3/OpenVario-linux-openvario-image-testing-glibc-ipk-20167-openvario-7-PQ070.rootfs.img.gz?dl=0), it should have the problem fixed.

**Comment by Blaubart** [comment]
Thanks a lot!!!! It works perfectly!

**Comment by Blaubart** [comment]
How can I see, that it is merged to warrior?

**Comment by kedder** [comment]
I'll make a pull request, as soon as it merges, this issue will close, you'll get a notification (probably).

**Comment by Blaubart** [comment]
I compiled stable and testing version at the same day with the same sources. Touchscreen calibration with testing-image works, with stable not. It dosen't make sense, right??

**Comment by kedder** [comment]
@Blaubart, no, it does not. Does the officially released stable version have the same issue?

**Comment by Blaubart** [comment]
I will test next days.
Thanks for helping!!

**Comment by Blaubart** [comment]
It is the same with officially released stable version for PixelQi 7.0

**Comment by linuxianer99** [comment]
Checked content of image a few minutes ago.
So the PR is in the official release image. Checked the udev rules file.

Just to be sure:
The official testing image works
The official stable not ?

**Comment by Blaubart** [comment]
I tried self compiled testing image (works), self compiled stable image (dosen't work) and officially released stable image (dosen't work)

**Comment by kedder** [comment]
I'll check as soon as I get to my testing device, hopefully this evening.

**Comment by kedder** [comment]
Ok, I can confirm the problem. It seems like XCSoar-6.8 is interpreting the touch input somehow differently from 7. It should be fixable, but I can't do it till the next week.

**Comment by kedder** [comment]
@Blaubart, I figured it out. Touchscreen on xcsoar-6.8.x will work after #102 is merged.

**Comment by Blaubart** [comment]
great! Thanks for your help!!
