### ISSUE TITLE
Tophat and LK8000 not included

### ISSUE THREAD

**Issue by kedder** [Openvario/meta-openvario#20]
Apparently there was an option to run Tophat or LK8000 instead of XCSoar. We only ship XCSoar right now. We might want to ship these, but I'm not sure in which form.

**Comment by kedder** [comment]
@CazYokoyama mentioned there is a branch with Tophat and LK8000: 

>  tophat_lk8000 branch in git@github.com:CazYokoyama/meta-openvario.git

**Comment by linuxianer99** [comment]
@CazYokoyama : I am not sure if this builds with the new image. Can you please verify if the recipes still work ??

**Comment by linuxianer99** [comment]
@kedder Do we still have the strategy of shipping the other apps ?
Think as of the lean firmware strategy, we should offer them as installable packages ??

**Comment by MaxKellermann** [comment]
Since nobody has been working on this for at least two years (= no developer is interested), the decision on how to integrate other applications is premature, and should be postponed until there is a working and stable recipe.
