### ISSUE TITLE
Logo SVG file

### ISSUE THREAD

**Issue by MaxKellermann** [Openvario/meta-openvario#200]
The logo should be a SVG file which will be converted to raster bitmap during the build. This way, we don't need many copies of the same BMP files, and generate those we want in any resolution for all display sizes.
Does somebody have a SVG file of it?

**Comment by mihu-ov** [comment]
![Open_Vario_Logo_Vectorgrafic](https://user-images.githubusercontent.com/60506612/150697418-42bb5056-8604-4e00-a919-545d1017af2a.svg)

**Comment by MaxKellermann** [comment]
Thanks, who is the copyright holder and what is the license?

**Comment by MaxKellermann** [comment]
This is .... not a SVG file. Technically, it is, but it is just a SVG container with an embedded PNG raster file, encoded in base64. No vector graphics at all, not scalable.

**Comment by mihu-ov** [comment]
I will check with Guido.

**Comment by mihu-ov** [comment]
Just to let you know Guido is working on it.

**Comment by MacflySF27** [comment]
Hi! My daughter made new “refurbished” logos.
The favourite one with a color gradient -and one with two colours (just in case…)

…hope this works!?

all the best - Guido

![Open_Vario_Newlogo_Vektorgraphic_Gradient](https://user-images.githubusercontent.com/99092867/152653805-8f9093ba-1d33-426e-bb29-40518a0f4ed9.svg)
![Open_Vario_Newlogo_Vektorgraphic_Solid](https://user-images.githubusercontent.com/99092867/152653815-9f2c16ba-1eea-4f26-b9ea-bc98d79418be.svg)

**Comment by lordfolken** [comment]
Hello guide, this looks really good and is in the proper format.
 I have one request however: The logo should be visible also on a black/dark background, would some shading be possible?
We should also create an AUTHORS file and credit her for her work.

**Comment by lordfolken** [comment]
#258

**Comment by MacflySF27** [comment]
Hello!
I just talked to my daughter - and she said that shading or vignetting ist not the way to go - "industry std." is a second logo where the dark colours are inverted.
What do you think about this idea?

**Comment by lordfolken** [comment]
I'm fine with an inverted logo aswell :)

**Comment by lordfolken** [comment]
@linuxianer99 where in the source tree should we add this? We have a Data/graphics/ in XCSoar, perhaps a similar approach?

**Comment by MaxKellermann** [comment]
I'll take care of integrating it, and auto-generate the BMP files.

**Comment by MaxKellermann** [comment]
@MacflySF27 for the git commit adding the SVG file, what shall I enter as its author?
What is the license? (You could say choose between GPLv3 and CC-BY-SA at will, so both licenses are covered, and the logo could be used by both OpenVario documentation and the software)

**Comment by MacflySF27** [comment]
Hi!
Finally my daughter did all the work - her name is 
Andrea Probst and you can link her homepage
www.andpro.work.
License - sorry no idea - your choice.

Here is the inverted logo - i think it looks great on a black background:
![Open_Vario_Newlogo_Vektorgraphic-Inverted](https://user-images.githubusercontent.com/99092867/152885402-5f28ace0-8e20-45d3-bcc7-c87d21511d56.svg)

here is a screenshot with black background:
![image](https://user-images.githubusercontent.com/99092867/152885490-71ca1282-a6a9-4240-a68b-b3878833701b.png)
