### ISSUE TITLE
psplash missing --angle switch

### ISSUE THREAD

**Issue by lordfolken** [Openvario/meta-openvario#201]
# issue:
machine: ov57-lvds
OV starts, the uboot splash screen is 90 degree rotated (after setting it in ovmenu settings).
Then the bootsplash animation done with psplash isn't rotated (0)
The ovmenu appears and is rotated 90 degrees again.

# Things i tried
When starting ```psplash --angle 90```from the shell, the boot splash is being displayed at the correct angle of 90.

# How to fix
I found a patch https://patchwork.openembedded.org/patch/123181/ that seems to read to read from /etc/rotation. However that doesn't solve our problem, as we have a (afaik) a static ramdisk. 

So I would suggest to add a small shell script to the ramdisk, that reads /proc/cmdline and parses the fbcon variable. 

The fbcon=rotate:3 switch would cause the shell script to output 90 as the argument for psplash.

Note: 
If found this, and in the basic machconf file there seems to be a general "CAN_ROTATE" switch. I haven't really found where this is being interpreted, but I think its the official way to go, and should be added to our machconf.
https://docs.yoctoproject.org/current/singleindex.html#adding-a-formfactor-configuration-file

**Comment by lordfolken** [comment]
hmm the /etc/rotation doesn't seem to work.

**Comment by lordfolken** [comment]
So i had a look at the psplash-init script and modifed it:
```bash
#!/bin/sh 
### BEGIN INIT INFO
# Provides:             psplash
# Required-Start:
# Required-Stop:
# Default-Start:        S
# Default-Stop:
### END INIT INFO

. /etc/default/rcS
export PSPLASH_FIFO_DIR

if [ ! -e /dev/fb0 ]; then
    echo "Framebuffer /dev/fb0 not detected"
    echo "Boot splashscreen disabled"
    exit 0;
fi

read cmdline < /proc/cmdline
for x in $cmdline; do
        case $x in
        psplash=false)
		echo "boot splashscreen disabled" 
		exit 0;
                ;;
        esac
done

rotation=0
read cmdline < /proc/cmdline
for x in $cmdline; do 
       case $x in 
         fbcon=rotate:0)
             rotation=0
             ;;
         fbcon=rotate:3)
             rotation=90
             ;;
         fbcon=rotate:2)
             rotation=180
             ;;
         fbcon=rotate:1)
             rotation=270
             ;;
       esac
done

[ -d $PSPLASH_FIFO_DIR ] || mkdir -p $PSPLASH_FIFO_DIR
if ! mountpoint -q $PSPLASH_FIFO_DIR; then
	mount tmpfs -t tmpfs $PSPLASH_FIFO_DIR -o,size=40k
fi

/usr/bin/psplash --angle $rotation 
```
But now it seems that the psplash uses the systemd.service file.

**Comment by lordfolken** [comment]
Ok the above approach was wrong, as we are using systemd service of psplash now. 

I have a working solution: 

in the psplash.service file i added the --angle " ${ROTATION}" switch. 
and an EnvironemntFile=/etc/rotation
the environmentfile containes: ROTATION=0

I extended ovmenu-ng to write the /etc/rotation file according to the selection. 

What i don't like is to have the setting in two places, once for the framebuffer and once for the bootsplash screen. 

Alas the uboot kernel parameteres need fbcon=rotate=3, wheras --angle needs degrees. i.e. 90.

My current challenge is to add this to bitbake.
The /etc/rotation file needs to be installed, or else the splash screen will not show on the first boot.

**Comment by linuxianer99** [comment]
@lordfolken Think this is closed with #219  right ?

**Comment by lordfolken** [comment]
correct.

**Comment by linuxianer99** [comment]
@lordfolken Thanks :-)
