### ISSUE TITLE
Mouse wheel scrolling is inverted

### ISSUE THREAD

**Issue by lordfolken** [Openvario/meta-openvario#228]
When hooking up a normal usb mouse, the scrolling with the wheel is inverted compared to a desktop PC.

For example: 
 * in the waypoint list, scrolling up on the mouse will scroll down on the list.
 * Zooming on the map scrolling up on the mouse zooms out

**Comment by linuxianer99** [comment]
@lordfolken Should we still leave this open ?

**Comment by lordfolken** [comment]
Its just an issue i noticed. It really only matters if you attach a (normal USB) HID mouse.
