### ISSUE TITLE
Integrate documentation repository also in meta-openvario ??

### ISSUE THREAD

**Issue by linuxianer99** [Openvario/meta-openvario#255]
Does it make sense to integrate the documentation repository also in the meta-openvario repository ??
So the manuals are also in sync with the current source code ...

**Comment by MaxKellermann** [comment]
Yes, please. I never understood why many projects have separate documentation repositories.

**Comment by linuxianer99** [comment]
Do you have a suggestion where to place in the directory structure ??

**Comment by MaxKellermann** [comment]
Directory `doc` contains everything the old `documentation` repository contains.
We could easily import all existing commits from the repository, so its history is preserved. (You know, I like to preserve history.)
