### ISSUE TITLE
chattr comand not found

### ISSUE THREAD

**Issue by Blaubart** [Openvario/meta-openvario#289]
chattr is no longer implemented at OV image. It is pretty usefull for club gliders.

**Comment by linuxianer99** [comment]
Can make a PR please ??

**Comment by MaxKellermann** [comment]
Why is chattr useful? I don't think the OV base image needs to include each and every exotic tool.

**Comment by Blaubart** [comment]
I agree with you Max, but we use this tool to lock the XCSoar profile on our club planes. We all know it, everyone fiddles with the device and in the end nothing works anymore. And then we have work to get everything up and running again over the weekend. Withe chattr XCSoar always runs in the fixed version. If certain members want to use different settings, they get their own profile. This makes using the OpenVario in clubs much easier!

**Comment by Blaubart** [comment]
by the way, i2cdetect has also disappeared from the image. The program is mandatory if you build your OV by your own and want to check whether you have soldered all the sensors correctly.

**Comment by linuxianer99** [comment]
@Blaubart What are you doing in detail with chattr ?
Can is be done with chmod ??

**Comment by Blaubart** [comment]
chmod does not, as far as I can tell, make a file immutable. chattr can do that. With this you are able to make the XCSoar profile in club aircraft unchangeable, so that the OpenVario always starts in the same configuration.
Otherwise the system will be fiddled with unnecessarily, nothing will run reliably and acceptance in the club will be low. Not to mention the work that people like me have to do to fix everything!

**Comment by linuxianer99** [comment]
what about chmod and remove the "write" attribute ?
Sorry, but I don't see why chattr is needed ...

**Comment by Blaubart** [comment]
Hmmm, I will give a try!

**Comment by Blaubart** [comment]
I tried chmod 555 openvario.prf and it dosen't work. I was able to change the profile and after reboot, changes are still there!
