### ISSUE TITLE
bluetooth tools not available in version 22086

### ISSUE THREAD

**Issue by condoratberlin** [Openvario/meta-openvario#293]
I'm using version OpenVario-linux-openvario-image-glibc-ipk-22086-openvario-7-CH070 provided by Uwe Augustin.
I just see, that the hcitool is not available any more, which was earlier versions.
Due to this I#m not able to configure my bluetooth connection to my nano logger anymore. Is there a different way to use bluetooth?
Or are some packages are missing in the build?

**Comment by linuxianer99** [comment]
So the build should be as small as possible ... 
There is a discussion ongoing here #181 regarding different types of images ... 
Maybe you can post your input there ...
