### ISSUE TITLE
Installation of a damping for the Vario

### ISSUE THREAD

**Issue by Blaubart** [Openvario/meta-openvario#294]
I'm not sure whether my suggestion should be implemented in OpenVario or in XCSoar. But the vario that can be displayed next to the NavBoxes is very restless. Some seem to be bothered by that. Would it be an option to add adjustable damping?

**Comment by hpmax** [comment]
The config file for sensord should contain a Kalman filter gain, by adjusting this you should be able to make it respond slower.  There should be a better approach, but that's there now.

**Comment by Blaubart** [comment]
Thanks! That would at least be a temporary solution. Unfortunately, since I have absolutely no idea about it, I need a more detailed description of how I could try it out.
Thank you very much!!

**Comment by Blaubart** [comment]
Thanks, I will try

**Comment by hpmax** [comment]
I can't recall for sure,  but I think it should be: vario_config>0.  I don't think there is any other restriction.

**Comment by mihu-ov** [comment]
You probably need to setup some kind of simulation to find meaningful values. Trial and error in flight doesn't work well.

**Comment by hpmax** [comment]
I think you can record data and replay it.  There's no mechanism to adjust vario_config in flight.   You'd have to edit the file and restart sensord.
