### ISSUE TITLE
Build is broken: Stuff for variod/sensord missing

### ISSUE THREAD

**Issue by realtimepeople** [Openvario/meta-openvario#301]
Something goes wrong with the latest build, 
see screenshot.
Regards
Klaus

**Comment by realtimepeople** [comment]
![Screenshot_20220503_182552](https://user-images.githubusercontent.com/62793036/166498770-ac40ed86-98f0-47e6-8cd9-d62d9373e417.png)

**Comment by MaxKellermann** [comment]
Duplicate of https://github.com/Openvario/meta-openvario/issues/306 (that one is better because it has error messages as text and not as screenshot).
