### ISSUE TITLE
xcsoar-testing build fails - probably missing sox dependency

### ISSUE THREAD

**Issue by Scumi** [Openvario/meta-openvario#319]
The build of openvario-image-testing fails during the xcsoar-testing step. Probably due to the change from ffmpeg to sox in XCSoar/XCSoar@b134244bb356a3d656b5bd2981085ff8da19598f

I wasn't successful (yet) in making the change within the openvario build environment.

**Comment by linuxianer99** [comment]
Fixed by 
Openvario/ovbuild-container@dd68da7
