### ISSUE TITLE
Firmware 17119 and STF

### ISSUE THREAD

**Issue by RobLS3** [Openvario/meta-openvario#326]
Hello,

I'm new to the forum and I hope you can help me. I'm looking for firmware 17119 for my 5.7" Open Vario, because the latest version freezes more often. I have a Stefly Open Vario with a sensor board and stick remote control. Can anyone tell me how I can save my profiles? And how do I use the button the back of the stick remote control to switch between STF and Vario? Unfortunately, my English is only halfway understandable via a translator :-D

Thanks in advance, regards Robert

**Comment by mihu-ov** [comment]
This is for development and not for user support. Please ask in the XCSoar forum.
