### ISSUE TITLE
fixed malformed POV,C, sentences

### ISSUE THREAD

**Issue by bomilkar** [Openvario/meta-openvario#40]
Heads up.
Please inspect this PR:
https://github.com/XCSoar/XCSoar/pull/367

I fixed sentences for POV,C,WL and POV,C,BU and I hope I didn't break anything.

**Comment by kedder** [comment]
Thanks @bomilkar! It will be included in the next -testing image.

**Comment by bomilkar** [comment]
It's already there. I "repo sync" it this morning an the binary has it.
Works like a charm. My vario is happy!

**Comment by linuxianer99** [comment]
will be included in next testing image
