### ISSUE TITLE
No opkg feed for openvario_7_CH070 variant

### ISSUE THREAD

**Issue by kedder** [Openvario/meta-openvario#56]
opkg feed for `openvario_7_CH070` variant is missing https://ftp.openvario.org/feed-warrior/. This will result in errors when trying to use opkg on this openvario flavor. 

Please upload respective packages to the server.

**Comment by linuxianer99** [comment]
upload done ..
@kedder : please check again

**Comment by kedder** [comment]
@linuxianer99 the dir is on ftp in the right location, but it is missing `Packages` and `Packages.gz` files, so `opkg` cannot use them. These files can be generated with bitbake:

```sh
MACHINE=openvario-7-CH070 bitbake package-index
```

Then the `Packages` files will be generated in `tmp/deploy/ipk/openvario_7_CH070/`

**Comment by linuxianer99** [comment]
sorry. i did the index only for PQ070 ...
give me a few minutes ...

**Comment by linuxianer99** [comment]
done.
Please try again ..

**Comment by kedder** [comment]
Awesome! It works now!
