### ISSUE TITLE
Docker image: rsync is missing

### ISSUE THREAD

**Issue by kedder** [Openvario/meta-openvario#72]
Newer kernel build system relies on `rsync` utility (to install header files), but it is missing in `linuxianer99/ovbuild` docker image.

@linuxianer99, please add `rsync` to the docker image and publish it on docker hub.

**Comment by linuxianer99** [comment]
@kedder : Done!
New image on docker hub

**Comment by Blaubart** [comment]
is it possible that rsync is missing again??
